version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    platform: linux/amd64
    env_file: .env
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
      - ./themes:/var/www/html/wp-content/themes
volumes:
  db_data:
